spring:
  datasource:
    url: ""
    username: ""
    password: ""
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true



logging:
  level:
    com.tutorial: debug


